version: 0.2

env::
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r CICD/flask-app/requirements.txt
  build:
    commands:
      - echo "Building the project..."
      - cd CICD/flask-app
      - echo "Building images..."
      - docker build -t "$DOCKER_REGISTRY_URL/myapp:latest"
      - docker push "$DOCKER_REGISTRY_URL/myapp:latest"
  post_build:
    commands:
      - echo "Build completed on `date`"